### ISSUE TITLE
SQL Azure DB exception

### ISSUE THREAD

**Issue by danielEsains** [olahallengren/sql-server-maintenance-solution#752]
**Description of the issue**

The script [IndexOptimize] is being excecuted in a Elastic Job for a SQL Azure DB, the job start to work with no issus but after some time its  throw the following exception:

System.AggregateException: One or more errors occurred.
   ---> Command failed: A severe error occurred on the current command.  The results, if any, should be discarded. 
   ---> Microsoft.Data.SqlClient.SqlException: A severe error occurred on the current command.  The results, if any, should be discarded. 
      at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
       in D:\a\_work\1\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\SqlClient\SqlConnection.cs:line 2287 
          at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) 
          in D:\a\_work\1\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\SqlClient\TdsParser.cs:line 1693  
            at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, 
            BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) in
             D:\a\_work\1\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\SqlClient\TdsParser.cs:line 0
                 at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
                  in D:\a\_work\1\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\SqlClient\SqlDataReader.cs:line 1333 
                     at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData() in
                      D:\a\_work\1\s\src\Microsoft.Data.SqlClient\netfx\src\Microsoft\Data\SqlClient\SqlDataReader.cs:line 283  
                        at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal,
                         Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted) ........"

**SQL Server version and edition**
Microsoft SQL Azure (RTM) - 12.0.2000.8  	May 22 2023 22:22:02  	Copyright (C) 2022 Microsoft Corporation 

**Version of the script**
Version: 2022-12-03 17:23:44 

**What command are you executing?**

exec [dbo].[IndexOptimize]
@Databases = 'ods',
@FragmentationLow = NULL,
@FragmentationMedium = 'INDEX_REORGANIZE,INDEX_REBUILD_ONLINE,INDEX_REBUILD_OFFLINE',
@FragmentationHigh = 'INDEX_REBUILD_ONLINE,INDEX_REBUILD_OFFLINE',
@FragmentationLevel1 = 5,
@FragmentationLevel2 = 30,
@MinNumberOfPages = 1000,
@MaxNumberOfPages = 300000,
@SortInTempdb = 'Y',
@Indexes = 'ALL_INDEXES',-ods.dbo.dim_player_personal.ix_pres_updated_at_dim_player_personal',
@LogToTable = 'Y',
@LOBCompaction = 'Y',
@TimeLimit= 14400,
@PartitionLevel = 'Y',
@MSShippedObjects = 'Y'

**What output are you getting?**

Command failed: A severe error occurred on the current command.  The results, if any, should be discarded.

**Comment by olahallengren** [comment]
This looks like a bug in Azure SQL Database. Is it still happening?

**Comment by m60freeman** [comment]
I get these on occasion from Azure SQL DB. It is caused by some Azure
infrastructure hiccup, and nothing can be done about it.

**Comment by olahallengren** [comment]
Have you opened a case with Microsoft support? It would be helpful to understand what’s happening.

**Comment by Stiffboard** [comment]
Have you checked if any snapshot backup runs in the middle of indexing? Short snapshot freeze might cause it to fail? Check backupset in msdb.

**Comment by m60freeman** [comment]
> Have you opened a case with Microsoft support? It would be helpful to understand what’s happening.

I have not. I have a Runbook executing a PS script to run your SPs to update stats daily and rebuild indexes weekly via schedules in 6 Azure Regions for 140 databases. I get an error roughly once per week and there is no pattern for which database or region is involved. It always completes successfully for that database on the next execution.

**Comment by olahallengren** [comment]
@m60freeman, is it the same issue whether the stored procedure is executed from an Elastic Job or a Runbook?

**Comment by olahallengren** [comment]
It would be interesting to know what is causing it. A failover? A network issue? Or maybe a bug in SQL Server?

**Comment by m60freeman** [comment]
> @m60freeman, is it the same issue whether the stored procedure is executed from an Elastic Job or a Runbook?

We have only used a Runbook so far.

**Comment by olahallengren** [comment]
>We have only used a Runbook so far. So I get it from a Runbook and the OP is getting it from an Elastic Job. I fully believe this is an Azure issue and nothing to do with IndexOptimize.

That is good to know. Thank you for reporting the issue.

**Comment by olahallengren** [comment]
As this does not appear to be an issue with IndexOptimize, I will close this issue for now. Please comment if you discover any additional details.
